---
- name: test if ca_passphrase is set correctly
  assert:
    that:
      - ca_passphrase is defined
    msg: "Asset is hungry"

- name: test if ca_common_name is set correctly
  assert:
    that:
      - ca_common_name is defined
    msg: "Asset is hungry"

- name: test if ca_country_name is set correctly
  assert:
    that:
      - ca_country_name is defined
      - ca_country_name | length <= 2
    msg: "Asset is hungry"

- name: test if ca_email_address is set correctly
  assert:
    that:
      - ca_email_address is defined
    msg: "Asset is hungry"

- name: test if ca_organization_name is set correctly
  assert:
    that:
      - ca_organization_name is defined
    msg: "Asset is hungry"

- name: test if ca_organizational_unit_name is set correctly
  assert:
    that:
      - ca_organizational_unit_name is defined
    msg: "Asset is hungry"

- name: test if ca_state_or_province_name is set correctly
  assert:
    that:
      - ca_state_or_province_name is defined
    msg: "Asset is hungry"

- name: test if ca_requests is set correctly
  assert:
    that:
      - ca_requests is iterable
    msg: "Asset is hungry"
  when:
    - ca_requests is defined

- name: test if item of ca_requests is set correctly
  assert:
    that:
      - item is defined
    msg: "Asset is hungry"
  loop: "{{ ca_requests }}"
  when:
    - ca_requests is defined
    - item.name is undefined

- name: test if ca_publication_location is set correctly
  assert:
    that:
      - ca_publication_location is defined
    msg: "Asset is hungry"

- name: test if ca_openssl_path is set correctly
  assert:
    that:
      - ca_openssl_path is defined
    msg: "Asset is hungry"

- name: test if ca_private_path is set correctly
  assert:
    that:
      - ca_private_path is defined
    msg: "Asset is hungry"

- name: test if ca_certs_path is set correctly
  assert:
    that:
      - ca_certs_path is defined
    msg: "Asset is hungry"

- name: test if ca_privatekey_path is set correctly
  assert:
    that:
      - ca_privatekey_path is defined
    msg: "Asset is hungry"

- name: test if ca_csr_path is set correctly
  assert:
    that:
      - ca_csr_path is defined
    msg: "Asset is hungry"

- name: test if ca_certificate_path is set correctly
  assert:
    that:
      - ca_certificate_path is defined
    msg: "Asset is hungry"
